### ISSUE TITLE
Send Message To

### ISSUE THREAD

**Issue by hirenshah** [ahcantao/WhatsApp_status_tracker#1]
Can you send a message to yourself with this?

**Comment by ahcantao** [comment]
> Can you send a message to yourself with this?

No and Yes! And I will explain why.

**No:** On WhastApp you can not explicitly have a chat with yourself, even if you save your own contact it is not showed on the WhatsApp list when you search for it (on new chat); BUT...

**Yes:** We can work around this by creating a new group adding anyone you know (only 1 person is needed), then removing this person from the group. That is it! Now you can send the message to yourself by setting the variable: informed_contact_name = 'my_group_name'

Make sure you set the name exactly as it is on your app and star the project if you enjoy it.

**Comment by hirenshah** [comment]
I've been tinkering and firstly I think there needs to be a warning to users / additional development to handle scenarios where the contact to message doesn't exist.

On my Android phone, I added my number in the Contacts app, which automatically synced and gave me the option to message myself on WhatsApp. 

Fortunately I was just testing with a friend because I set the recipient as the contact I created for myself, but WhatsApp ignored that and only displayed my number.

I could message myself through WhatsApp on my phone etc because the chat was now present, BUT because the incorrect name was set for the person receiving the alerts... they ended up being sent to the friend I was test spying on. 

Please see screenshots of messages being sent to the person I was test spying on and also my contact being available to message myself. The contacts name is my number so if I define that I think I will be able to message myself. 

![Screenshot_20200217-223759_WhatsApp](https://user-images.githubusercontent.com/418112/74690239-3a3aba80-51d6-11ea-8624-c2f3bb0695a6.jpg)
![Screenshot_20200217-223910_WhatsApp](https://user-images.githubusercontent.com/418112/74690268-5b031000-51d6-11ea-8f59-659d0e42859c.jpg)
